package Interface;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import BD.BDFavoritos;
import BD.BDTodosPokemon;
import BD.BDUsuario;
import BD.Conexion;
import Datos.ClsFavoritos;
import Datos.ClsPokemon;
import Datos.ClsUsuario;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.*;
import static java.sql.DriverManager.getConnection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import java.util.Objects;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
public class VentanaPokedex extends javax.swing.JFrame {

    BufferedImage buffer1 =null;
    Image imagen1 = null;
    int contador = 0;
    
    Statement estado;
    ResultSet resultadoConsulta;
    Connection conexion;
    
    @Override
    public void paint(Graphics g){
        super.paintComponents(g);
        Graphics2D g2 =(Graphics2D) imagenPokemon.getGraphics();
        
        g2.drawImage(buffer1, 0,0,imagenPokemon.getWidth(),imagenPokemon.getHeight(),null);
        
    }
    
    
    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        initComponents();
        p5.setVisible(false);
        
        try {
            //imagen1 = ImageIO.read(getClass().getResource("/imagenes/back-white.png"));
            
            imagen1 =ImageIO.read(new File("C:\\Users\\ramos\\Downloads\\PokemonsFinal\\Pokemons\\black-white.png"));
        } catch (IOException ex) {
            ex.printStackTrace(System.out);
        }
        
        buffer1 = (BufferedImage) imagenPokemon.createImage(
                imagenPokemon.getWidth(),
                imagenPokemon.getHeight());
        
        Graphics2D g2 = buffer1.createGraphics();
        
        dibujaElPokemonQueEstaEnLaPosicion(30);
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String JDBC_URL="jdbc:mysql://localhost:3306/test?zeroDateTimeBehavior=convertToNull&useSSL=false&useTimezone=true&serverTimezone=UTC"; 
            
            conexion = DriverManager.getConnection(JDBC_URL,"root","loso");
            estado = conexion.createStatement();
            
            
            
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace(System.out);
            System.out.println("Hay error de clase no encontrada");
        } catch (SQLException ex) {
           ex.printStackTrace(System.out);
            System.out.println("Hay error de BD");
        }
        
        
        
    }

    
    private void dibujaElPokemonQueEstaEnLaPosicion(int posicion){
        int fila = posicion / 31;
        int columna = posicion % 31;
        
        Graphics2D g2 = (Graphics2D) buffer1.getGraphics();
        g2.setColor(Color.CYAN);
        
        g2.fillRect(0, 0, //pinta el fondo del jpanel negro
                imagenPokemon.getWidth(),
                imagenPokemon.getHeight()); 
        
        
        g2.drawImage(imagen1,
                0,  //posicion X inicial dentro del jpanel 
                0,  // posicion Y inicial dentro del jpanel
                imagenPokemon.getWidth(), //ancho del jpanel
                imagenPokemon.getHeight(), //alto del jpanel
                columna*96, //posicion inicial X dentro de la imagen de todos los pokemon
                fila*96, //posicion inicial Y dentro de la imagen de todos los pokemon
                columna*96 + 96, //posicion final X
                fila*96 + 96, //posicion final Y
                null  //si no lo pones no va
                );
        
        repaint();
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p6 = new javax.swing.JPanel();
        txtusuario = new javax.swing.JTextField();
        butonRegistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        butonlogin1 = new javax.swing.JButton();
        txtcontraseña = new javax.swing.JPasswordField();
        jCheckBox3 = new javax.swing.JCheckBox();
        p5 = new javax.swing.JPanel();
        imagenPokemon = new javax.swing.JPanel();
        nombrePokemon = new javax.swing.JLabel();
        izq = new javax.swing.JButton();
        der = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpokedex = new javax.swing.JTable();
        idpokemon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        controlador1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        btImprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        controlador2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        p6.setBackground(new java.awt.Color(204, 204, 255));

        butonRegistrar.setText("Iniciar");
        butonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("USUARIO:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("CONTRASEÑA:");

        jLabel4.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 0));
        jLabel4.setText("INCIA SECION PARA PODER INGRESAR AL SISTEMA");

        butonlogin1.setText("Registrar");
        butonlogin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butonlogin1ActionPerformed(evt);
            }
        });

        txtcontraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontraseñaActionPerformed(evt);
            }
        });

        jCheckBox3.setBackground(new java.awt.Color(255, 204, 0));
        jCheckBox3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        jCheckBox3.setText("Mostrar Contraseña");
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p6Layout = new javax.swing.GroupLayout(p6);
        p6.setLayout(p6Layout);
        p6Layout.setHorizontalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p6Layout.createSequentialGroup()
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p6Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(butonlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p6Layout.createSequentialGroup()
                                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(p6Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(26, 26, 26)
                                        .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p6Layout.createSequentialGroup()
                                        .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(p6Layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtcontraseña)))
                                        .addGap(57, 57, 57)))
                                .addComponent(butonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        p6Layout.setVerticalGroup(
            p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(butonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(butonlogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(p6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel4)
                .addGap(23, 23, 23)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(p6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox3)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 347, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        nombrePokemon.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        nombrePokemon.setText("nombre");

        izq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        izq.setText("<== Izquierda");
        izq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                izqActionPerformed(evt);
            }
        });

        der.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        der.setText("derecha ==>");
        der.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derActionPerformed(evt);
            }
        });

        tbpokedex.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbpokedex);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Agregar a favoritos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        controlador1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        controlador1.setText("Id Pokemon");

        jButton4.setBackground(new java.awt.Color(204, 255, 204));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 51, 51));
        jButton4.setText("CERRAR SECION");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btImprimir.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btImprimir.setText("Imprimir PDF");
        btImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btImprimirActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Buscar entre los pokemons");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("Ver todos los datos de los pokemon");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Ver mis favoritos");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        controlador2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        controlador2.setText("Opciones de busqueda de Pokemon");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(controlador2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(controlador2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1428, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(imagenPokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(p5Layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(nombrePokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(p5Layout.createSequentialGroup()
                                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(p5Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(izq)
                                        .addGap(18, 18, 18)
                                        .addComponent(der))
                                    .addGroup(p5Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(p5Layout.createSequentialGroup()
                                        .addGap(115, 115, 115)
                                        .addComponent(idpokemon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(controlador1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p5Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(controlador1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(idpokemon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(izq, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(der, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(imagenPokemon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(nombrePokemon))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addComponent(btImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p5Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(p6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(p5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void pokee(){
         BDFavoritos basedatos = new BDFavoritos();
        String names []={"id", "name", "forme_name", "forme_base_pokemon_id", "generation_id", "evolution_chain_id", "evolution_parent_pokemon_id", "evolution_method_id", "evolution_parameter", "height", "weight", "species", "color", "pokemon_shape_id", "habitat", "gender_rate", "capture_rate", "base_experience", "base_happiness", "gen1_internal_id", "is_baby", "has_gen4_fem_sprite", "has_gen4_fem_back_sprite"};
        
        List<ClsPokemon> Imprimir =basedatos.dtpokemon(Integer.parseInt(idpokemon.getText()));
        dato =new String[Imprimir.size()][23];
        int centinela=0;
        for (ClsPokemon centro : Imprimir) {
            dato[centinela][0]=centro.getId()+"";
            dato[centinela][1]=centro.getName();
            dato[centinela][2]=centro.getForme_name();
            dato[centinela][3]=centro.getForme_base_pokemon_id();
            dato[centinela][4]=centro.getGeneration_id()+"";
            dato[centinela][5]=centro.getEvolution_chain_id()+"";
            dato[centinela][6]=centro.getEvolution_parent_pokemon_id()+"";
            dato[centinela][7]=centro.getEvolution_method_id()+"";
            dato[centinela][8]=centro.getEvolution_parameter()+"";
            dato[centinela][9]=centro.getHeight()+"";
            dato[centinela][10]=centro.getWeight()+"";
            dato[centinela][11]=centro.getSpecies();
            dato[centinela][12]=centro.getColor();
            dato[centinela][13]=centro.getPokemon_shape_id()+"";
            dato[centinela][14]=centro.getHabitat();
            dato[centinela][15]=centro.getGender_rate()+"";
            dato[centinela][16]=centro.getCapture_rate()+"";
            dato[centinela][17]=centro.getBase_experience()+"";
            dato[centinela][18]=centro.getBase_happiness()+"";
            dato[centinela][19]=centro.getGen1_internal_id()+"";
            dato[centinela][20]=centro.getIs_baby()+"";
            dato[centinela][21]=centro.getHas_gen4_fem_sprite()+"";
            dato[centinela][22]=centro.getHas_gen4_fem_back_sprite()+"";

            centinela++;
        }

        tbpokedex.setModel(new DefaultTableModel(dato,names));

    }
    
    private void derActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derActionPerformed
        // TODO add your handling code here:
        dibujaElPokemonQueEstaEnLaPosicion(contador);
        
        try {
            resultadoConsulta = estado.
                    executeQuery("select * from pokemon where id="+(contador + 1));

            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));
                idpokemon.setText(resultadoConsulta.getString(1));
                idpokemon.setEnabled(true);
                pokee();
                
                
            } else {
                nombrePokemon.setText("Este chucho no esta e el pokedex");
                idpokemon.setText("sin resultado");
                idpokemon.setEnabled(false);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        contador++;
        if (contador >= 649){
            contador = 649;
        }
        
        
        
    }//GEN-LAST:event_derActionPerformed

    private void izqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_izqActionPerformed
         // TODO add your handling code here:
        //evento cuando el usr de click en izquierdo
       dibujaElPokemonQueEstaEnLaPosicion(contador);
       
        
        try {
            resultadoConsulta = estado.
                    executeQuery("select * from pokemon where id="+(contador + 1));

            if (resultadoConsulta.next()){
                nombrePokemon.setText(resultadoConsulta.getString(2));
                idpokemon.setText(resultadoConsulta.getString(1));
                idpokemon.setEnabled(true);
                pokee();
                
            } else {
                nombrePokemon.setText("Este chucho no esta e el pokedex");
                idpokemon.setText("sin resultado");
                idpokemon.setEnabled(false);

                
      
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        contador--;
        if(contador <=0){
            contador=2;
        }
    }//GEN-LAST:event_izqActionPerformed
    
    String dato[][];
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        Desplegar x=new Desplegar(); //Despliege de una ventana
//        x.setVisible(true);
//        this.setVisible(false);

        BDTodosPokemon basedatos = new BDTodosPokemon();
        String names []={"id", "name", "forme_name", "forme_base_pokemon_id", "generation_id", "evolution_chain_id", "evolution_parent_pokemon_id", "evolution_method_id", "evolution_parameter", "height", "weight", "species", "color", "pokemon_shape_id", "habitat", "gender_rate", "capture_rate", "base_experience", "base_happiness", "gen1_internal_id", "is_baby", "has_gen4_fem_sprite", "has_gen4_fem_back_sprite"};
        List<ClsPokemon> Imprimir =basedatos.selectglobal();
        dato =new String[Imprimir.size()][23];
        int centinela=0;
        for (ClsPokemon centro : Imprimir) {
            dato[centinela][0]=centro.getId()+"";
            dato[centinela][1]=centro.getName();
            dato[centinela][2]=centro.getForme_name();
            dato[centinela][3]=centro.getForme_base_pokemon_id();
            dato[centinela][4]=centro.getGeneration_id()+"";
            dato[centinela][5]=centro.getEvolution_chain_id()+"";
            dato[centinela][6]=centro.getEvolution_parent_pokemon_id()+"";
            dato[centinela][7]=centro.getEvolution_method_id()+"";
            dato[centinela][8]=centro.getEvolution_parameter()+"";
            dato[centinela][9]=centro.getHeight()+"";
            dato[centinela][10]=centro.getWeight()+"";
            dato[centinela][11]=centro.getSpecies();
            dato[centinela][12]=centro.getColor();
            dato[centinela][13]=centro.getPokemon_shape_id()+"";
            dato[centinela][14]=centro.getHabitat();
            dato[centinela][15]=centro.getGender_rate()+"";
            dato[centinela][16]=centro.getCapture_rate()+"";
            dato[centinela][17]=centro.getBase_experience()+"";
            dato[centinela][18]=centro.getBase_happiness()+"";
            dato[centinela][19]=centro.getGen1_internal_id()+"";
            dato[centinela][20]=centro.getIs_baby()+"";
            dato[centinela][21]=centro.getHas_gen4_fem_sprite()+"";
            dato[centinela][22]=centro.getHas_gen4_fem_back_sprite()+"";

            centinela++;
        }

        tbpokedex.setModel(new DefaultTableModel(dato,names));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ClsFavoritos fv = new ClsFavoritos();
        BDFavoritos basedat = new BDFavoritos();
        if ("".equals(idpokemon.getText())) {
            JOptionPane.showMessageDialog(null,"Los campos esta vacios mi pana, llenalos para usar esta opcion");
        }else{
            fv.setId_pokemon(Integer.parseInt(idpokemon.getText()));
            fv.setUsuario(txtusuario.getText());
            basedat.insert(fv,fv.getId_pokemon(),aa);
            JOptionPane.showMessageDialog(null,"Listo, vendedor agregado");

        }

    }//GEN-LAST:event_jButton2ActionPerformed

    public String aa;
     ClsUsuario registro = new ClsUsuario();
         BDFavoritos basedatos = new BDFavoritos ();
    private void butonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonRegistrarActionPerformed
        BDUsuario db=new  BDUsuario();

        registro.setUsuario(txtusuario.getText());
        registro.setPass(txtcontraseña.getText());
        aa = txtusuario.getText();

        if ("".equals(txtusuario.getText()) || "".equals(txtcontraseña.getText())) {
            JOptionPane.showMessageDialog(null,"Oh no mi pan, rellene todos los campos para utlizar esta opcion");
        }else{
            if(db.Validar(registro)){
                p5.setVisible(true);
                p6.setVisible(false);
                txtusuario.setText("");
                txtcontraseña.setText("");
            }else{
                JOptionPane.showMessageDialog(null,"Usuario o Contraseña iconrrecta","ADVERTENCIA",JOptionPane.WARNING_MESSAGE);
                txtusuario.setText("");txtcontraseña.setText("");
            }

        }
        
    }//GEN-LAST:event_butonRegistrarActionPerformed

    private void butonlogin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butonlogin1ActionPerformed
        NuevoUsuario centinela=new  NuevoUsuario();
        centinela.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_butonlogin1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String names []={"id", "name", "forme_name", "forme_base_pokemon_id", "generation_id", "evolution_chain_id", "evolution_parent_pokemon_id", "evolution_method_id", "evolution_parameter", "height", "weight", "species", "color", "pokemon_shape_id", "habitat", "gender_rate", "capture_rate", "base_experience", "base_happiness", "gen1_internal_id", "is_baby", "has_gen4_fem_sprite", "has_gen4_fem_back_sprite"};
        BDFavoritos basedato = new BDFavoritos ();
        List<ClsPokemon> Imprimir = basedato.select(aa);
        System.out.println(aa);
        dato =new String[Imprimir.size()][23];
        int centinela=0;
        for (ClsPokemon centro : Imprimir) {
            dato[centinela][0]=centro.getId()+"";
            dato[centinela][1]=centro.getName();
            dato[centinela][2]=centro.getForme_name();
            dato[centinela][3]=centro.getForme_base_pokemon_id();
            dato[centinela][4]=centro.getGeneration_id()+"";
            dato[centinela][5]=centro.getEvolution_chain_id()+"";
            dato[centinela][6]=centro.getEvolution_parent_pokemon_id()+"";
            dato[centinela][7]=centro.getEvolution_method_id()+"";
            dato[centinela][8]=centro.getEvolution_parameter()+"";
            dato[centinela][9]=centro.getHeight()+"";
            dato[centinela][10]=centro.getWeight()+"";
            dato[centinela][11]=centro.getSpecies();
            dato[centinela][12]=centro.getColor();
            dato[centinela][13]=centro.getPokemon_shape_id()+"";
            dato[centinela][14]=centro.getHabitat();
            dato[centinela][15]=centro.getGender_rate()+"";
            dato[centinela][16]=centro.getCapture_rate()+"";
            dato[centinela][17]=centro.getBase_experience()+"";
            dato[centinela][18]=centro.getBase_happiness()+"";
            dato[centinela][19]=centro.getGen1_internal_id()+"";
            dato[centinela][20]=centro.getIs_baby()+"";
            dato[centinela][21]=centro.getHas_gen4_fem_sprite()+"";
            dato[centinela][22]=centro.getHas_gen4_fem_back_sprite()+"";

            centinela++;

            tbpokedex.setModel(new DefaultTableModel(dato,names));

        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        p6.setVisible(true);
        p5.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        BusquedaPokemon x=new BusquedaPokemon(); 
         x.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btImprimirActionPerformed
        try {
            

            Connection conn = getConnection("test");
            
            JasperReport reporte= null;
            String path="src\\main\\java\\Reporte\\report1.jasper";
             
            reporte = (JasperReport) JRLoader.loadObjectFromFile(path);//CASTEO
            JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);
            
            JasperViewer view = new JasperViewer(jprint,false);
            
            view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);//para que se cierre
            
            view .setVisible(true);// para que sea visible
        } catch (JRException ex) {
            ex.printStackTrace(System.out);
           JOptionPane.showMessageDialog(null, "ERROR, NO SE CREEO EL PDF");
            
                
            } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btImprimirActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        if(jCheckBox1.isSelected()){
            txtcontraseña.setEchoChar((char)0);
        }else{
            txtcontraseña.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void txtcontraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontraseñaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btImprimir;
    private javax.swing.JButton butonRegistrar;
    private javax.swing.JButton butonlogin1;
    private javax.swing.JLabel controlador1;
    private javax.swing.JLabel controlador2;
    private javax.swing.JButton der;
    private javax.swing.JTextField idpokemon;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton izq;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombrePokemon;
    public javax.swing.JPanel p5;
    private javax.swing.JPanel p6;
    private javax.swing.JTable tbpokedex;
    private javax.swing.JPasswordField txtcontraseña;
    public javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
